language: node_js
node_js:
  - '14'
jdk:
  - oraclejdk8
addons:
  chrome: stable
  sonarcloud: true
install:
  - npm install
  - npm ci
script:
  - nohup npm run start &
  - sleep 3
  - npm run coverage
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=acalvom -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=acalvom_test-ci -X


